import novruzImage from '../../../public/images/novruz.png';
import mahireImage from '../../../public/icons/mahire.svg';
import meqsedImage from '../../../public/icons/meqsed.svg';
import ilaheImage from '../../../public/icons/ilahe.svg';

export const agentsData = [
  {
    id: 1,
    name: 'Novruz',
    fullName: 'Novruz Əliyev',
    role: 'CEO & Founder',
    image: novruzImage,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    email: 'novruz.aliyev@realestate.az',
    phone: '+994501234567',
    age: 42,
    address: 'Nəsimi rayonu, Azadlıq prospekti 12, Bakı',
    education: 'Azərbaycan Dövlət İqtisad Universiteti, MBA',
    about1: '15 illik təcrübəyə malik daşınmaz əmlak üzrə mütəxəssis. Bakı şəhərində 500-dən çox uğurlu əmlak alqı-satqısına rəhbərlik edib.',
    about2: 'Müştəri məmnuniyyəti və peşəkar xidmət göstərilməsinə həmişə prioritet verirəm. Komandamızla birlikdə, hər bir müştərinin arzularını reallığa çevirməyə çalışırıq.',
  },

  {
    id: 2,
    name: 'Mahirə',
    fullName: 'Mahirə Həsənova',
    role: 'Real Estate Developer',
    image: mahireImage,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    email: 'mahire.hasanova@realestate.az',
    phone: '+994552345678',
    age: 35,
    address: 'Yasamal rayonu, Ə.Rəcəbli küçəsi 45, Bakı',
    education: 'Azərbaycan Memarlıq və İnşaat Universiteti, Memarlıq',
    about1: 'Müasir yaşayış komplekslərinin layihələndirilməsi və inkişafı sahəsində 10 illik təcrübə. Davamlılıq və innovativ dizayn prinsiplərinə sadiqəm.',
    about2: 'Hər bir layihəni müştərilərin ehtiyaclarını və ətraf mühiti nəzərə alaraq hazırlayıram. Keyfiyyət və funksionallıq mənim əsas prioritetlərimdir.',
  },

  {
    id: 3,
    name: 'Məqsəd',
    fullName: 'Məqsəd Quliyev',
    role: 'Listing Agent',
    image: meqsedImage,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    email: 'meqsed.quliyev@realestate.az',
    phone: '+994503456789',
    age: 29,
    address: 'Nərimanov rayonu, Təbriz küçəsi 89, Bakı',
    education: 'Bakı Dövlət Universiteti, Biznes İdarəetməsi',
    about1: 'Əmlak satışı və marketinq strategiyaları üzrə ixtisaslaşmışam. Müştərilərin əmlakını ən sərfəli şəkildə bazara çıxarmaqda peşəkaram.',
    about2: 'Rəqəmsal marketinq alətlərindən istifadə edərək, əmlakların maksimum görünürlüyünü təmin edirəm. Hər bir əmlakın unikal xüsusiyyətlərini vurğulayıram.',
  },

  {
    id: 4,
    name: 'İlahə',
    fullName: 'İlahə Məmmədova',
    role: 'Buyer Agent',
    image: ilaheImage,
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    email: 'ilahe.memmedova@realestate.az',
    phone: '+994554567890',
    age: 31,
    address: 'Səbail rayonu, Nizami küçəsi 23, Bakı',
    education: 'Azərbaycan Turizm və Menecment Universiteti, İqtisadiyyat',
    about1: 'Alıcılara ideal ev tapmaqda kömək etməyi sevirəm. Hər bir müştərinin büdcəsinə və ehtiyaclarına uyğun ən yaxşı variantları təqdim edirəm.',
    about2: 'Bazar təhlili və danışıqlar aparmaqda güclüyəm. Müştərilərimə əmlak alışı prosesində tam dəstək göstərirəm.',
  },

  {
    id: 5,
    name: 'Elvin',
    fullName: 'Elvin Əhmədov',
    role: 'Commercial Property Specialist',
    image: novruzImage,
    email: 'elvin.ahmadov@realestate.az',
    phone: '+994505678901',
    age: 38,
    address: 'Xətai rayonu, Məmməd Araz küçəsi 67, Bakı',
    education: 'Azərbaycan Dövlət İqtisad Universiteti, Maliyyə',
    about1: 'Kommersiya əmlakı, ofis və ticarət mərkəzləri üzrə mütəxəssisəm. Biznes sahiblərinə investisiya qərarlarında məsləhət verirəm.',
    about2: 'Bazar trendlərini izləyərək, ən gəlirli kommersiya əmlakı fürsətlərini müəyyənləşdirirəm.',
  },

  {
    id: 6,
    name: 'Səbinə',
    fullName: 'Səbinə Rəsulov',
    role: 'Luxury Property Consultant',
    image: mahireImage,
    email: 'sebine.rasulov@realestate.az',
    phone: '+994556789012',
    age: 33,
    address: 'Nəsimi rayonu, Dilara Əliyeva küçəsi 156, Bakı',
    education: 'Xarici Dillər Universiteti, Beynəlxalq Əlaqələr və MBA',
    about1: 'Lüks əmlak seqmentində ixtisaslaşmışam. VIP müştərilərə eksklüziv xidmət və gizlilik təmin edirəm.',
    about2: 'Premium əmlakların marketinqi və yüksək dəyərli əmlak əməliyyatlarında təcrübəliyəm. İngilis və rus dillərində sərbəst danışıram.',
  },

  {
    id: 7,
    name: 'Orxan',
    fullName: 'Orxan Mustafayev',
    role: 'Investment Advisor',
    image: meqsedImage,
    email: 'orxan.mustafayev@realestate.az',
    phone: '+994507890123',
    age: 40,
    address: 'Binəqədi rayonu, Ə.Qarayev prospekti 34, Bakı',
    education: 'Azərbaycan Dövlət İqtisad Universiteti, İqtisadiyyat doktorluğu',
    about1: 'Daşınmaz əmlak investisiyaları və portfel idarəetməsi üzrə 12 illik təcrübəyə malikəm. İnvestorlar üçün maksimum gəlir strategiyaları hazırlayıram.',
    about2: 'Əmlak bazarının dinamikasını dərin təhlil edərək, uzunmüddətli investisiya planları təklif edirəm.',
  },

  {
    id: 8,
    name: 'Aynur',
    fullName: 'Aynur İsmayılova',
    role: 'Rental Specialist',
    image: ilaheImage,
    email: 'aynur.ismayilova@realestate.az',
    phone: '+994558901234',
    age: 27,
    address: 'Nizami rayonu, Süleyman Rəhimov küçəsi 78, Bakı',
    education: 'Bakı Biznes Universiteti, Biznes İdarəetməsi',
    about1: 'İcarə əmlakı üzrə mütəxəssisəm. Ev sahibləri və kirayəçilər arasında ən uyğun əlaqələri qururam.',
    about2: 'Qısa və uzunmüddətli icarə müqavilələrinin hazırlanması və idarə olunmasında peşəkaram. Hər iki tərəfin maraqlarını qoruyuram.',
  },

  {
    id: 9,
    name: 'Rauf',
    fullName: 'Rauf Bayramov',
    role: 'Property Valuation Expert',
    image: novruzImage,
    email: 'rauf.bayramov@realestate.az',
    phone: '+994509012345',
    age: 45,
    address: 'Səbail rayonu, İçərişəhər, Bakı',
    education: 'Azərbaycan Memarlıq və İnşaat Universiteti, Mülki Mühəndislik',
    about1: 'Əmlak qiymətləndirilməsi və ekspertizası sahəsində 18 illik təcrübə. Texniki yoxlamalar və dəqiq qiymətləndirmə xidmətləri göstərirəm.',
    about2: 'Bank kreditləri, sığorta və məhkəmə prosesləri üçün peşəkar qiymətləndirmə hesabatları hazırlayıram.',
  },

  {
    id: 10,
    name: 'Günel',
    fullName: 'Günel Əliyeva',
    role: 'New Construction Specialist',
    image: mahireImage,
    email: 'gunel.aliyeva@realestate.az',
    phone: '+994550123456',
    age: 28,
    address: 'Xəzər rayonu, Şüvəlan qəsəbəsi, Bakı',
    education: 'Qərb Universiteti, Arxitektura',
    about1: 'Yeni tikili layihələr üzrə ixtisaslaşmışam. Tikintinin ilk mərhələsindən müştərilərə məsləhət verirəm və ən yaxşı şərtləri təmin edirəm.',
    about2: 'İnşaat keyfiyyətinin monitorinqi və tikinti şirkətləri ilə əlaqələndirmədə təcrübəliyəm.',
  },

  {
    id: 11,
    name: 'Tural',
    fullName: 'Tural Həsənov',
    role: 'Regional Market Analyst',
    image: meqsedImage,
    email: 'tural.hasanov@realestate.az',
    phone: '+994501234568',
    age: 36,
    address: 'Nərimanov rayonu, Əhmədli metrosu yaxınlığı, Bakı',
    education: 'Azərbaycan Dövlət İqtisad Universiteti, Statistika və İqtisad Analizi',
    about1: 'Bölgələr üzrə bazar araşdırmaları və trend təhlilləri aparıram. Müştərilərə məlumat əsaslı qərar qəbuletmə üçün dəstək göstərirəm.',
    about2: 'Əmlak bazarının gələcək inkişaf istiqamətlərini proqnozlaşdırır və strateji planlaşdırmada kömək edirəm.',
  },

  {
    id: 12,
    name: 'Leyla',
    fullName: 'Leyla Cəfərova',
    role: 'Client Relations Manager',
    image: ilaheImage,
    email: 'leyla.cafarova@realestate.az',
    phone: '+994552345679',
    age: 30,
    address: 'Yasamal rayonu, 8 Noyabr prospekti 112, Bakı',
    education: 'Bakı Slavyan Universiteti, Psixologiya və İdarəetmə',
    about1: 'Müştəri məmnuniyyəti və münasibətlərin idarə edilməsi üzrə mütəxəssisəm. Hər bir müştəriyə fərdi yanaşma tətbiq edirəm.',
    about2: 'Satış sonrası xidmətlər və uzunmüddətli müştəri əlaqələrinin qurulmasında təcrübəliyəm. Komandamızın və müştərilərimizin arasında körpü rolunu oynayıram.',
  },
];

export default agentsData;