export const blogData = [
  {
    image: "/images/BlogPhoto1.jpg",
    id: 1,
    title: "Ev alarkən qaçınmaq üçün ən yaxşı 10 səhv",
    description: "Etiam eget elementum elit. Aenean dignissim dapibus vestibulum",
    day: "28",
    month: "İyl",
    year: "2025",
    date: "22.07.2025",
  },
  {
    image: "/images/BlogPhoto2.jpg",
    id: 2,
    title: "Tez Satış üçün Evinizi Necə Hazırlamaq olar",
    description: "Nullam odio lacus, dictum quis pretium congue, vehicula venenatis nunc.",
    day: "08",
    month: "Avg",
    year: "2024",
    date: "15.08.2024",
  },
  {
    image: "/images/BlogPhoto3.jpg",
    id: 3,
    title: "İlk dəfə ev satanlar üçün 5 məsləhət",
    description: "In hac habitasse platea dictumst. Phasellus vel velit vel augue maximus.",
    day: "26",
    month: "Yan",
    year: "2026",
    date: "01.01.2026",
  },
  {
    image: "/images/BlogPhoto1.jpg",
    id: 4,
    title: "Ev alarkən qaçınmaq üçün ən yaxşı 10 səhv",
    description: "Etiam eget elementum elit. Aenean dignissim dapibus vestibulum",
    day: "28",
    month: "İyl",
    year: "2025",
    date: "22.07.2025",
  },
  {
    image: "/images/BlogPhoto2.jpg",
    id: 5,
    title: "Tez Satış üçün Evinizi Necə Hazırlamaq olar",
    description: "Nullam odio lacus, dictum quis pretium congue, vehicula venenatis nunc.",
    day: "08",
    month: "Avg",
    year: "2024",
    date: "15.08.2024",
  },
  {
    image: "/images/BlogPhoto3.jpg",
    id: 6,
    title: "İlk dəfə ev satanlar üçün 5 məsləhət",
    description: "In hac habitasse platea dictumst. Phasellus vel velit vel augue maximus.",
    day: "26",
    month: "Yan",
    year: "2026",
    date: "01.01.2026",
  },
  {
    image: "/images/BlogPhoto1.jpg",
    id: 7,
    title: "Ev alarkən qaçınmaq üçün ən yaxşı 10 səhv",
    description: "Etiam eget elementum elit. Aenean dignissim dapibus vestibulum",
    day: "28",
    month: "İyl",
    year: "2025",
    date: "22.07.2025",
  },
  {
    image: "/images/BlogPhoto2.jpg",
    id: 8,
    title: "Tez Satış üçün Evinizi Necə Hazırlamaq olar",
    description: "Nullam odio lacus, dictum quis pretium congue, vehicula venenatis nunc.",
    day: "08",
    month: "Avg",
    year: "2024",
    date: "15.08.2024",
  },
  {
    image: "/images/BlogPhoto3.jpg",
    id: 9,
    title: "İlk dəfə ev satanlar üçün 5 məsləhət",
    description: "In hac habitasse platea dictumst. Phasellus vel velit vel augue maximus.",
    day: "26",
    month: "Yan",
    year: "2026",
    date: "01.01.2026",
  },
  {
    image: "/images/BlogPhoto1.jpg",
    id: 10,
    title: "Ev alarkən qaçınmaq üçün ən yaxşı 10 səhv",
    description: "Etiam eget elementum elit. Aenean dignissim dapibus vestibulum",
    day: "28",
    month: "İyl",
    year: "2025",
    date: "22.07.2025",
  },
  {
    image: "/images/BlogPhoto2.jpg",
    id: 11,
    title: "Tez Satış üçün Evinizi Necə Hazırlamaq olar",
    description: "Nullam odio lacus, dictum quis pretium congue, vehicula venenatis nunc.",
    day: "08",
    month: "Avg",
    year: "2024",
    date: "15.08.2024",
  },
  {
    image: "/images/BlogPhoto3.jpg",
    id: 12,
    title: "İlk dəfə ev satanlar üçün 5 məsləhət",
    description: "In hac habitasse platea dictumst. Phasellus vel velit vel augue maximus.",
    day: "26",
    month: "Yan",
    year: "2026",
    date: "01.01.2026",
  },
  {
    image: "/images/BlogPhoto1.jpg",
    id: 13,
    title: "Ev alarkən qaçınmaq üçün ən yaxşı 10 səhv",
    description: "Etiam eget elementum elit. Aenean dignissim dapibus vestibulum",
    day: "28",
    month: "İyl",
    year: "2025",
    date: "22.07.2025",
  },
  {
    image: "/images/BlogPhoto2.jpg",
    id: 14,
    title: "Tez Satış üçün Evinizi Necə Hazırlamaq olar",
    description: "Nullam odio lacus, dictum quis pretium congue, vehicula venenatis nunc.",
    day: "08",
    month: "Avg",
    year: "2024",
    date: "15.08.2024",
  },
  {
    image: "/images/BlogPhoto3.jpg",
    id: 15,
    title: "İlk dəfə ev satanlar üçün 5 məsləhət",
    description: "In hac habitasse platea dictumst. Phasellus vel velit vel augue maximus.",
    day: "26",
    month: "Yan",
    year: "2026",
    date: "01.01.2026",
  },
];
