import image1 from "../../../public/images/ev1.jpg";

export const RealEstateData = [
  {
    id: 1,
    photo: image1,
    elan_id: "#123456",
    owner: "Sadiq",
    property_type: "Yeni tikili",
    price: "125,500 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 16,
    totalFloors: 20,
    room: 5,
    area: "90 m²",
    land_area: "-",
    header: "90 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 234 88 30",
    note: "-",
    application_date: "20/11/2025 11:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 2,
    photo: image1,
    elan_id: "#124789",
    owner: "Əli Məmmədov",
    property_type: "Köhnə tikili",
    price: "98,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 8,
    totalFloors: 12,
    room: 3,
    area: "75 m²",
    land_area: "-",
    header: "85 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 456 77 88",
    note: "-",
    application_date: "19/11/2025 14:22",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 3,
    photo: image1,
    elan_id: "#125332",
    owner: "Leyla Həsənova",
    property_type: "Köhnə tikili",
    price: "250,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 2,
    totalFloors: 5,
    room: 6,
    area: "180 m²",
    land_area: "300 m²",
    header: "200 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 234 56 89",
    note: "-",
    application_date: "18/11/2025 09:15",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 4,
    photo: image1,
    elan_id: "#126445",
    owner: "Rəşad Əliyev",
    property_type: "Yeni tikili",
    price: "145,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Əla",
    floor: 12,
    totalFloors: 20,
    room: 4,
    area: "110 m²",
    land_area: "-",
    header: "110 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "051 789 45 23",
    note: "-",
    application_date: "20/11/2025 16:30",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 5,
    photo: image1,
    elan_id: "#127556",
    owner: "Nigar Quliyeva",
    property_type: "Köhnə tikili",
    price: "72,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Orta",
    floor: 3,
    totalFloors: 5,
    room: 2,
    area: "55 m²",
    land_area: "-",
    header: "60 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 123 98 76",
    note: "-",
    application_date: "17/11/2025 11:00",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 6,
    photo: image1,
    elan_id: "#128667",
    owner: "Elşən Babayev",
    property_type: "Həyət evi / Bağ evi",
    price: "420,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 1,
    totalFloors: 1,
    room: 8,
    area: "350 m²",
    land_area: "600 m²",
    header: "400 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "012 456 78 90",
    note: "-",
    application_date: "20/11/2025 08:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 7,
    photo: image1,
    elan_id: "#129778",
    owner: "Səbinə Məhərrəmova",
    property_type: "Köhnə tikili",
    price: "88,500 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 7,
    totalFloors: 9,
    room: 3,
    area: "82 m²",
    land_area: "-",
    header: "85 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "077 345 67 89",
    note: "-",
    application_date: "19/11/2025 13:20",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 8,
    photo: image1,
    elan_id: "#130889",
    owner: "Kamran Hüseynov",
    property_type: "Yeni tikili",
    price: "195,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 15,
    totalFloors: 25,
    room: 7,
    area: "200 m²",
    land_area: "-",
    header: "220 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 999 88 77",
    note: "-",
    application_date: "20/11/2025 10:15",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 9,
    photo: image1,
    elan_id: "#131990",
    owner: "Təranə Əhmədova",
    property_type: "Köhnə tikili",
    price: "65,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 4,
    totalFloors: 5,
    room: 2,
    area: "48 m²",
    land_area: "-",
    header: "50 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 777 66 55",
    note: "-",
    application_date: "16/11/2025 15:40",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 10,
    photo: image1,
    elan_id: "#132101",
    owner: "Orxan Rzayev",
    property_type: "Yeni tikili",
    price: "135,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 10,
    totalFloors: 15,
    room: 4,
    area: "95 m²",
    land_area: "-",
    header: "100 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 888 99 00",
    note: "-",
    application_date: "20/11/2025 12:50",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 11,
    photo: image1,
    elan_id: "#133212",
    owner: "Günel Məmmədova",
    property_type: "Köhnə tikili",
    price: "108,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 5,
    totalFloors: 10,
    room: 3,
    area: "78 m²",
    land_area: "-",
    header: "80 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "051 555 44 33",
    note: "-",
    application_date: "18/11/2025 14:25",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 12,
    photo: image1,
    elan_id: "#134323",
    owner: "Fuad Qasımov",
    property_type: "Köhnə tikili",
    price: "185,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Əla",
    floor: 1,
    totalFloors: 3,
    room: 5,
    area: "140 m²",
    land_area: "250 m²",
    header: "150 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 666 77 88",
    note: "-",
    application_date: "19/11/2025 09:30",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 13,
    photo: image1,
    elan_id: "#135434",
    owner: "Aynur İbrahimova",
    property_type: "Köhnə tikili",
    price: "92,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Orta",
    floor: 6,
    totalFloors: 14,
    room: 3,
    area: "70 m²",
    land_area: "-",
    header: "72 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 444 55 66",
    note: "-",
    application_date: "20/11/2025 11:10",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 14,
    photo: image1,
    elan_id: "#136545",
    owner: "Rəsul Mustafayev",
    property_type: "Köhnə tikili",
    price: "78,500 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Zəif",
    floor: 2,
    totalFloors: 5,
    room: 2,
    area: "52 m²",
    land_area: "-",
    header: "55 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 333 22 11",
    note: "-",
    application_date: "17/11/2025 16:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 15,
    photo: image1,
    elan_id: "#137656",
    owner: "Zülfiyyə Əliyeva",
    property_type: "Yeni tikili",
    price: "158,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 18,
    totalFloors: 22,
    room: 4,
    area: "125 m²",
    land_area: "-",
    header: "130 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 111 22 33",
    note: "-",
    application_date: "20/11/2025 15:20",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 16,
    photo: image1,
    elan_id: "#138767",
    owner: "Elnur Həsənov",
    property_type: "Həyət evi / Bağ evi",
    price: "35,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 1,
    totalFloors: 1,
    room: 1,
    area: "25 m²",
    land_area: "-",
    header: "25 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "077 999 88 77",
    note: "-",
    application_date: "19/11/2025 10:05",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
];

export const columnHeaders = [
  { key: "photo", label: "Şəkil" },
  { key: "elan_id", label: "Elan ID" },
  { key: "owner", label: "Mülkiyyətçi adı" },
  { key: "property_type", label: "Əmlak növü" },
  { key: "price", label: "Qiymət" },
  { key: "announcement_type", label: "Elan növü" },
  { key: "exit", label: "Çıxarış" },
  { key: "mortgage", label: "İpoteka" },
  { key: "repair_type", label: "Təmir növü" },
  { key: "floor", label: "Mərtəbə" },
  { key: "totalFloors", label: "Ümumi Mərtəbə" },
  { key: "room", label: "Otaq" },
  { key: "area", label: "Sahə" },
  { key: "land_area", label: "Torpaq sahəsi" },
  { key: "header", label: "Başlıq" },
  { key: "city", label: "Şəhər" },
  { key: "district", label: "Rayon" },
  { key: "settlement", label: "Qəsəbə" },
  { key: "metro", label: "Metro" },
  { key: "owner_phone_number", label: "Mülkiyyətçi nömrəsi" },
  { key: "note", label: "Qeyd" },
  { key: "application_date", label: "Müraciət tarixi" },
  { key: "description", label: "Təsvir" },
];

export const azeSettlement = [
  "Aşağı Güzdək",
  "Atyalı",
  "Ceyranbatan",
  "Çiçək",
  "Digah",
  "Fatmayı",
  "Görədil",
  "Güzdək",
  "Hökməli",
  "Köhnə Corat",
  "Qobu",
  "Masazır",
  "Mehdiabad",
  "Məmmədli",
  "Novxanı",
  "Pirəkəşkül",
  "Saray",
  "Yeni Corat",
  "Zuğulba",
  "2-ci Alatava",
  "28 May",
  "6-cı mikrorayon",
  "7-ci mikrorayon",
  "8-ci mikrorayon",
  "9-cu mikrorayon",
  "Biləcəri",
  "Binəqədi",
  "Xocəsən",
  "Xutor",
  "M.Ə.Rəsulzadə",
  "Sulutəpə",
  "Ağ şəhər",
  "Əhmədli",
  "Həzi Aslanov",
  "Köhnə Günəşli",
  "NZS",
  "Binə",
  "Buzovna",
  "Dübəndi",
  "Gürgən",
  "Qala",
  "Mərdəkan",
  "Şağan",
  "Şimal DRES",
  "Şüvəlan",
  "Türkan",
  "Zirə",
  "Ələt",
  "Qızıldaş",
  "Qobustan",
  "Lökbatan",
  "Müşfiqabad",
  "Puta",
  "Sahil",
  "Səngəçal",
  "Şubanı",
  "Böyükşor",
  "1-ci mikrorayon",
  "2-ci mikrorayon",
  "3-cü mikrorayon",
  "4-cü mikrorayon",
  "5-ci mikrorayon",
  "Kubinka",
  "8-ci kilometr",
  "Keşlə",
  "Albalılıq",
  "Bakıxanov",
  "Balaxanı",
  "Bilgəh",
  "Kürdəxanı",
  "Maştağa",
  "Nardaran",
  "Pirşağı",
  "Ramana",
  "Sabunçu",
  "Savalan",
  "Sea Breeze",
  "Yeni Balaxanı",
  "Yeni Ramana",
  "Zabrat",
  "20-ci sahə",
  "Badamdar",
  "Bayıl",
  "Bibiheybət",
  "Şıxov",
  "Bahar",
  "Bülbülə",
  "Dədə Qorqud",
  "Əmircan",
  "Günəşli",
  "Hövsan",
  "Qaraçuxur",
  "Massiv A",
  "Massiv B",
  "Massiv D",
  "Massiv G",
  "Massiv V",
  "Suraxanı",
  "Şərq",
  "Yeni Günəşli",
  "Yeni Suraxanı",
  "Zığ",
  "Yasamal",
  "Yeni Yasamal",
];

export const azeCity = [
  "Ağcabədi",
  "Ağdaş",
  "Ağstafa",
  "Ağsu",
  "Astara",
  "Bakı",
  "Balakən",
  "Beyləqan",
  "Bərdə",
  "Biləsuvar",
  "Cəlilabad",
  "Daşkəsən",
  "Gədəbəy",
  "Gəncə",
  "Goranboy",
  "Göyçay",
  "Göygöl",
  "Hacıqabul",
  "Xaçmaz",
  "Xırdalan",
  "Xızı",
  "Xocalı",
  "Xudat",
  "İmişli",
  "İsmayıllı",
  "Kürdəmir",
  "Qax",
  "Qazax",
  "Qəbələ",
  "Qobustan",
  "Quba",
  "Qusar",
  "Lerik",
  "Lənkəran",
  "Masallı",
  "Mingəçevir",
  "Naxçıvan",
  "Neftçala",
  "Oğuz",
  "Saatlı",
  "Sabirabad",
  "Salyan",
  "Samux",
  "Siyəzən",
  "Sumqayıt",
  "Şabran",
  "Şamaxı",
  "Şəki",
  "Şəmkir",
  "Şirvan",
  "Şuşa",
  "Tərtər",
  "Tovuz",
  "Ucar",
  "Yardımlı",
  "Yevlax",
  "Zaqatala",
];

export const azeDistrict = [
  "Abşeron",
  "Binəqədi",
  "Xətai",
  "Xəzər",
  "Qaradağ",
  "Nərimanov",
  "Nəsimi",
  "Nizami",
  "Pirallahı",
  "Sabunçu",
  "Səbail",
  "Suraxanı",
  "Yasamal",
];

export const azeMetro = [
  "20 Yanvar",
  "28 May",
  "8 Noyabr",
  "Avtovağzal",
  "Azadlıq Prospekti",
  "Bakmil",
  "Dərnəgül",
  "Elmlər Akademiyası",
  "Əhmədli",
  "Gənclik",
  "Həzi Aslanov",
  "Xalqlar Dostluğu",
  "Xocəsən",
  "İçəri Şəhər",
  "İnşaatçılar",
  "Koroğlu",
  "Qara Qarayev",
  "Memar Əcəmi",
  "Neftçilər",
  "Nəriman Nərimanov",
  "Nəsimi",
  "Nizami",
  "Sahil",
  "Şah İsmayıl Xətai",
  "Ulduz",
];
