import image1 from "../../../public/images/ev1.jpg";

export const RealEstateData = [
  {
    id: 1,
    photo: image1,
    elan_id: "#123456",
    owner: "Sadiq",
    property_type: "Mənzil",
    price: "125,500 ",
    announcement_type: "Satılıq",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 16,
    totalFloors: 20,
    room: 5,
    area: "90 m²",
    land_area: "-",
    header: "90 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 234 88 30",
    note: "-",
    application_date: "20/11/2025 11:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 2,
    photo: image1,
    elan_id: "#124789",
    owner: "Əli Məmmədov",
    property_type: "Mənzil",
    price: "98,000 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 8,
    totalFloors: 12,
    room: 3,
    area: "75 m²",
    land_area: "-",
    header: "85 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 456 77 88",
    note: "-",
    application_date: "19/11/2025 14:22",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 3,
    photo: image1,
    elan_id: "#125332",
    owner: "Leyla Həsənova",
    property_type: "Mənzil",
    price: "250,000 ",
    announcement_type: "Satılıq",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 2,
    totalFloors: 5,
    room: 6,
    area: "180 m²",
    land_area: "300 m²",
    header: "200 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 234 56 89",
    note: "-",
    application_date: "18/11/2025 09:15",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 4,
    photo: image1,
    elan_id: "#126445",
    owner: "Rəşad Əliyev",
    property_type: "Mənzil",
    price: "145,000 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Əla",
    floor: 12,
    totalFloors: 20,
    room: 4,
    area: "110 m²",
    land_area: "-",
    header: "110 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "051 789 45 23",
    note: "-",
    application_date: "20/11/2025 16:30",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 5,
    photo: image1,
    elan_id: "#127556",
    owner: "Nigar Quliyeva",
    property_type: "Mənzil",
    price: "72,000 ",
    announcement_type: "Satılıq",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Orta",
    floor: 3,
    totalFloors: 5,
    room: 2,
    area: "55 m²",
    land_area: "-",
    header: "60 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 123 98 76",
    note: "-",
    application_date: "17/11/2025 11:00",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 6,
    photo: image1,
    elan_id: "#128667",
    owner: "Elşən Babayev",
    property_type: "Mənzil",
    price: "420,000 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 1,
    totalFloors: 1,
    room: 8,
    area: "350 m²",
    land_area: "600 m²",
    header: "400 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "012 456 78 90",
    note: "-",
    application_date: "20/11/2025 08:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 7,
    photo: image1,
    elan_id: "#129778",
    owner: "Səbinə Məhərrəmova",
    property_type: "Mənzil",
    price: "88,500 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 7,
    totalFloors: 9,
    room: 3,
    area: "82 m²",
    land_area: "-",
    header: "85 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "077 345 67 89",
    note: "-",
    application_date: "19/11/2025 13:20",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 8,
    photo: image1,
    elan_id: "#130889",
    owner: "Kamran Hüseynov",
    property_type: "Mənzil",
    price: "195,000 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 15,
    totalFloors: 25,
    room: 7,
    area: "200 m²",
    land_area: "-",
    header: "220 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 999 88 77",
    note: "-",
    application_date: "20/11/2025 10:15",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 9,
    photo: image1,
    elan_id: "#131990",
    owner: "Təranə Əhmədova",
    property_type: "Mənzil",
    price: "65,000 ",
    announcement_type: "Satılıq",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 4,
    totalFloors: 5,
    room: 2,
    area: "48 m²",
    land_area: "-",
    header: "50 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 777 66 55",
    note: "-",
    application_date: "16/11/2025 15:40",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 10,
    photo: image1,
    elan_id: "#132101",
    owner: "Orxan Rzayev",
    property_type: "Mənzil",
    price: "135,000 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 10,
    totalFloors: 15,
    room: 4,
    area: "95 m²",
    land_area: "-",
    header: "100 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 888 99 00",
    note: "-",
    application_date: "20/11/2025 12:50",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 11,
    photo: image1,
    elan_id: "#133212",
    owner: "Günel Məmmədova",
    property_type: "Mənzil",
    price: "108,000 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 5,
    totalFloors: 10,
    room: 3,
    area: "78 m²",
    land_area: "-",
    header: "80 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "051 555 44 33",
    note: "-",
    application_date: "18/11/2025 14:25",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 12,
    photo: image1,
    elan_id: "#134323",
    owner: "Fuad Qasımov",
    property_type: "Mənzil",
    price: "185,000 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Əla",
    floor: 1,
    totalFloors: 3,
    room: 5,
    area: "140 m²",
    land_area: "250 m²",
    header: "150 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 666 77 88",
    note: "-",
    application_date: "19/11/2025 09:30",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 13,
    photo: image1,
    elan_id: "#135434",
    owner: "Aynur İbrahimova",
    property_type: "Mənzil",
    price: "92,000 ",
    announcement_type: "Satılıq",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Orta",
    floor: 6,
    totalFloors: 14,
    room: 3,
    area: "70 m²",
    land_area: "-",
    header: "72 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 444 55 66",
    note: "-",
    application_date: "20/11/2025 11:10",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 14,
    photo: image1,
    elan_id: "#136545",
    owner: "Rəsul Mustafayev",
    property_type: "Mənzil",
    price: "78,500 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Zəif",
    floor: 2,
    totalFloors: 5,
    room: 2,
    area: "52 m²",
    land_area: "-",
    header: "55 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 333 22 11",
    note: "-",
    application_date: "17/11/2025 16:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 15,
    photo: image1,
    elan_id: "#137656",
    owner: "Zülfiyyə Əliyeva",
    property_type: "Mənzil",
    price: "158,000 ",
    announcement_type: "Satılıq",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 18,
    totalFloors: 22,
    room: 4,
    area: "125 m²",
    land_area: "-",
    header: "130 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 111 22 33",
    note: "-",
    application_date: "20/11/2025 15:20",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 16,
    photo: image1,
    elan_id: "#138767",
    owner: "Elnur Həsənov",
    property_type: "Mənzil",
    price: "35,000 ",
    announcement_type: "Satılıq",
    exit: "Yoxdur",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 1,
    totalFloors: 1,
    room: 1,
    area: "25 m²",
    land_area: "-",
    header: "25 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "077 999 88 77",
    note: "-",
    application_date: "19/11/2025 10:05",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  }
];

// Column headers in order (left to right)
export const columnHeaders = [
  { key: "photo", label: "Şəkil" },
  { key: "elan_id", label: "Elan ID" },
  { key: "owner", label: "Mülkiyyətçi adı" },
  { key: "property_type", label: "Əmlak növü" },
  { key: "price", label: "Qiymət" },
  { key: "announcement_type", label: "Elan növü" },
  { key: "exit", label: "Çıxarış" },
  { key: "mortgage", label: "İpoteka" }, 
  { key: "repair_type", label: "Təmir növü" },
  { key: "floor", label: "Mərtəbə" },
  { key: "totalFloors", label: "Ümumi Mərtəbə" },
  { key: "room", label: "Otaq" },
  { key: "area", label: "Sahə" },
  { key: "land_area", label: "Torpaq sahəsi" },
  { key: "header", label: "Başlıq" },
  { key: "city", label: "Şəhər" },
  { key: "district", label: "Rayon" },
  { key: "settlement", label: "Qəsəbə" },
  { key: "metro", label: "Metro" },
  { key: "owner_phone_number", label: "Mülkiyyətçi nömrəsi" },
  { key: "note", label: "Qeyd" },
  { key: "application_date", label: "Müraciət tarixi" },
  { key: "description", label: "Təsvir" },
];