import image1 from "../../../public/images/ev1.jpg";

export const RealEstateData = [
  {
    id: 1,
    photo: image1,
    announcementId: "#123456",
    owner: "Sadiq",
    propertyType: "Ofis",
    price: "125500",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 16,
    totalFloors: 20,
    room: 5,
    area: "90 m²",
    land_area: "-",
    header: "90 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 234 88 30",
    note: "-",
    application_date: "20/11/2025 11:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
    selectedCity: "Bakı",
    selectedDistrict: "Abşeron",
    selectedSettlement: "Qobu",
    longitude: 49.8671,
    latitude: 40.4093,
  },
  {
    id: 2,
    photo: image1,
    announcementId: "#124789",
    owner: "Əli Məmmədov",
    propertyType: "Qaraj",
    price: "98,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 8,
    totalFloors: 12,
    room: 3,
    area: "75 m²",
    land_area: "-",
    header: "85 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 456 77 88",
    note: "-",
    application_date: "19/11/2025 14:22",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 3,
    photo: image1,
    announcementId: "#125332",
    owner: "Leyla Həsənova",
    propertyType: "Köhnə tikili",
    price: "250,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 2,
    totalFloors: 5,
    room: 6,
    area: "180 m²",
    land_area: "300 ha",
    header: "200 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 234 56 89",
    note: "-",
    application_date: "18/11/2025 09:15",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 4,
    photo: image1,
    announcementId: "#126445",
    owner: "Rəşad Əliyev",
    propertyType: "Yeni tikili",
    price: "145,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Əla",
    floor: 12,
    totalFloors: 20,
    room: 4,
    area: "110 m²",
    land_area: "-",
    header: "110 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "051 789 45 23",
    note: "-",
    application_date: "20/11/2025 16:30",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 5,
    photo: image1,
    announcementId: "#127556",
    owner: "Nigar Quliyeva",
    propertyType: "Köhnə tikili",
    price: "72,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Orta",
    floor: 3,
    totalFloors: 5,
    room: 2,
    area: "55 m²",
    land_area: "-",
    header: "60 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 123 98 76",
    note: "-",
    application_date: "17/11/2025 11:00",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 6,
    photo: image1,
    announcementId: "#128667",
    owner: "Elşən Babayev",
    propertyType: "Həyət evi / Bağ evi",
    price: "420,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 1,
    totalFloors: 1,
    room: 8,
    area: "350 m²",
    land_area: "600 ha",
    header: "400 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "012 456 78 90",
    note: "-",
    application_date: "20/11/2025 08:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 7,
    photo: image1,
    announcementId: "#129778",
    owner: "Səbinə Məhərrəmova",
    propertyType: "Köhnə tikili",
    price: "88,500 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 7,
    totalFloors: 9,
    room: 3,
    area: "82 m²",
    land_area: "-",
    header: "85 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "077 345 67 89",
    note: "-",
    application_date: "19/11/2025 13:20",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 8,
    photo: image1,
    announcementId: "#130889",
    owner: "Kamran Hüseynov",
    propertyType: "Yeni tikili",
    price: "195,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 15,
    totalFloors: 25,
    room: 7,
    area: "200 m²",
    land_area: "-",
    header: "220 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 999 88 77",
    note: "-",
    application_date: "20/11/2025 10:15",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 9,
    photo: image1,
    announcementId: "#131990",
    owner: "Təranə Əhmədova",
    propertyType: "Köhnə tikili",
    price: "65,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 4,
    totalFloors: 5,
    room: 2,
    area: "48 m²",
    land_area: "-",
    header: "50 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 777 66 55",
    note: "-",
    application_date: "16/11/2025 15:40",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 10,
    photo: image1,
    announcementId: "#132101",
    owner: "Orxan Rzayev",
    propertyType: "Yeni tikili",
    price: "135,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 10,
    totalFloors: 15,
    room: 4,
    area: "95 m²",
    land_area: "-",
    header: "100 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 888 99 00",
    note: "-",
    application_date: "20/11/2025 12:50",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 11,
    photo: image1,
    announcementId: "#133212",
    owner: "Günel Məmmədova",
    propertyType: "Köhnə tikili",
    price: "108,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Zəif",
    floor: 5,
    totalFloors: 10,
    room: 3,
    area: "78 m²",
    land_area: "-",
    header: "80 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "051 555 44 33",
    note: "-",
    application_date: "18/11/2025 14:25",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 12,
    photo: image1,
    announcementId: "#134323",
    owner: "Fuad Qasımov",
    propertyType: "Köhnə tikili",
    price: "185,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Əla",
    floor: 1,
    totalFloors: 3,
    room: 5,
    area: "140 m²",
    land_area: "250 ha",
    header: "150 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 666 77 88",
    note: "-",
    application_date: "19/11/2025 09:30",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 13,
    photo: image1,
    announcementId: "#135434",
    owner: "Aynur İbrahimova",
    propertyType: "Köhnə tikili",
    price: "92,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Var",
    repair_type: "Orta",
    floor: 6,
    totalFloors: 14,
    room: 3,
    area: "70 m²",
    land_area: "-",
    header: "72 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "070 444 55 66",
    note: "-",
    application_date: "20/11/2025 11:10",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 14,
    photo: image1,
    announcementId: "#136545",
    owner: "Rəsul Mustafayev",
    propertyType: "Köhnə tikili",
    price: "78,500 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Yoxdur",
    repair_type: "Zəif",
    floor: 2,
    totalFloors: 5,
    room: 2,
    area: "52 m²",
    land_area: "-",
    header: "55 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "055 333 22 11",
    note: "-",
    application_date: "17/11/2025 16:45",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 15,
    photo: image1,
    announcementId: "#137656",
    owner: "Zülfiyyə Əliyeva",
    propertyType: "Yeni tikili",
    price: "158,000 ",
    announcement_type: "Satıram",
    exit: "Var",
    mortgage: "Var",
    repair_type: "Əla",
    floor: 18,
    totalFloors: 22,
    room: 4,
    area: "125 m²",
    land_area: "-",
    header: "130 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "050 111 22 33",
    note: "-",
    application_date: "20/11/2025 15:20",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
  {
    id: 16,
    photo: image1,
    announcementId: "#138767",
    owner: "Elnur Həsənov",
    propertyType: "Həyət evi / Bağ evi",
    price: "35,000 ",
    announcement_type: "Satıram",
    exit: "Yoxdur",
    mortgage: "Yoxdur",
    repair_type: "Orta",
    floor: 1,
    totalFloors: 1,
    room: 1,
    area: "25 m²",
    land_area: "-",
    header: "25 m²",
    city: "Bakı ş.",
    district: "Xəzər ray.",
    settlement: "Qala qəs.",
    metro: "Koroğlu",
    owner_phone_number: "077 999 88 77",
    note: "-",
    application_date: "19/11/2025 10:05",
    description: "5 otaqlı,tam təmirli dənizə yaxın məsafədə",
  },
];

export const columnHeaders = [
  { key: "photo", label: "Şəkil" },
  { key: "announcementId", label: "Elan ID" },
  { key: "owner", label: "Mülkiyyətçi adı" },
  { key: "propertyType", label: "Əmlak növü" },
  { key: "price", label: "Qiymət" },
  { key: "announcement_type", label: "Elan növü" },
  { key: "exit", label: "Çıxarış" },
  { key: "mortgage", label: "İpoteka" },
  { key: "repair_type", label: "Təmir növü" },
  { key: "floor", label: "Mərtəbə" },
  { key: "totalFloors", label: "Ümumi Mərtəbə" },
  { key: "room", label: "Otaq" },
  { key: "area", label: "Sahə" },
  { key: "land_area", label: "Torpaq sahəsi" },
  { key: "header", label: "Başlıq" },
  { key: "city", label: "Şəhər" },
  { key: "district", label: "Rayon" },
  { key: "settlement", label: "Qəsəbə" },
  { key: "metro", label: "Metro" },
  { key: "owner_phone_number", label: "Mülkiyyətçi nömrəsi" },
  { key: "note", label: "Qeyd" },
  { key: "application_date", label: "Müraciət tarixi" },
  { key: "description", label: "Təsvir" },
];

export const azeSettlement = [
  { value: "Aşağı Güzdək", label: "Aşağı Güzdək" },
  { value: "Atyalı", label: "Atyalı" },
  { value: "Ceyranbatan", label: "Ceyranbatan" },
  { value: "Çiçək", label: "Çiçək" },
  { value: "Digah", label: "Digah" },
  { value: "Fatmayı", label: "Fatmayı" },
  { value: "Görədil", label: "Görədil" },
  { value: "Güzdək", label: "Güzdək" },
  { value: "Hökməli", label: "Hökməli" },
  { value: "Köhnə Corat", label: "Köhnə Corat" },
  { value: "Qobu", label: "Qobu" },
  { value: "Masazır", label: "Masazır" },
  { value: "Mehdiabad", label: "Mehdiabad" },
  { value: "Məmmədli", label: "Məmmədli" },
  { value: "Novxanı", label: "Novxanı" },
  { value: "Pirəkəşkül", label: "Pirəkəşkül" },
  { value: "Saray", label: "Saray" },
  { value: "Yeni Corat", label: "Yeni Corat" },
  { value: "Zuğulba", label: "Zuğulba" },
  { value: "2-ci Alatava", label: "2-ci Alatava" },
  { value: "28 May", label: "28 May" },
  { value: "6-cı mikrorayon", label: "6-cı mikrorayon" },
  { value: "7-ci mikrorayon", label: "7-ci mikrorayon" },
  { value: "8-ci mikrorayon", label: "8-ci mikrorayon" },
  { value: "9-cu mikrorayon", label: "9-cu mikrorayon" },
  { value: "Biləcəri", label: "Biləcəri" },
  { value: "Binəqədi", label: "Binəqədi" },
  { value: "Xocəsən", label: "Xocəsən" },
  { value: "Xutor", label: "Xutor" },
  { value: "M.Ə.Rəsulzadə", label: "M.Ə.Rəsulzadə" },
  { value: "Sulutəpə", label: "Sulutəpə" },
  { value: "Ağ şəhər", label: "Ağ şəhər" },
  { value: "Əhmədli", label: "Əhmədli" },
  { value: "Həzi Aslanov", label: "Həzi Aslanov" },
  { value: "Köhnə Günəşli", label: "Köhnə Günəşli" },
  { value: "NZS", label: "NZS" },
  { value: "Binə", label: "Binə" },
  { value: "Buzovna", label: "Buzovna" },
  { value: "Dübəndi", label: "Dübəndi" },
  { value: "Gürgən", label: "Gürgən" },
  { value: "Qala", label: "Qala" },
  { value: "Mərdəkan", label: "Mərdəkan" },
  { value: "Şağan", label: "Şağan" },
  { value: "Şimal DRES", label: "Şimal DRES" },
  { value: "Şüvəlan", label: "Şüvəlan" },
  { value: "Türkan", label: "Türkan" },
  { value: "Zirə", label: "Zirə" },
  { value: "Ələt", label: "Ələt" },
  { value: "Qızıldaş", label: "Qızıldaş" },
  { value: "Qobustan", label: "Qobustan" },
  { value: "Lökbatan", label: "Lökbatan" },
  { value: "Müşfiqabad", label: "Müşfiqabad" },
  { value: "Puta", label: "Puta" },
  { value: "Sahil", label: "Sahil" },
  { value: "Səngəçal", label: "Səngəçal" },
  { value: "Şubanı", label: "Şubanı" },
  { value: "Böyükşor", label: "Böyükşor" },
  { value: "1-ci mikrorayon", label: "1-ci mikrorayon" },
  { value: "2-ci mikrorayon", label: "2-ci mikrorayon" },
  { value: "3-cü mikrorayon", label: "3-cü mikrorayon" },
  { value: "4-cü mikrorayon", label: "4-cü mikrorayon" },
  { value: "5-ci mikrorayon", label: "5-ci mikrorayon" },
  { value: "Kubinka", label: "Kubinka" },
  { value: "8-ci kilometr", label: "8-ci kilometr" },
  { value: "Keşlə", label: "Keşlə" },
  { value: "Albalılıq", label: "Albalılıq" },
  { value: "Bakıxanov", label: "Bakıxanov" },
  { value: "Balaxanı", label: "Balaxanı" },
  { value: "Bilgəh", label: "Bilgəh" },
  { value: "Kürdəxanı", label: "Kürdəxanı" },
  { value: "Maştağa", label: "Maştağa" },
  { value: "Nardaran", label: "Nardaran" },
  { value: "Pirşağı", label: "Pirşağı" },
  { value: "Ramana", label: "Ramana" },
  { value: "Sabunçu", label: "Sabunçu" },
  { value: "Savalan", label: "Savalan" },
  { value: "Sea Breeze", label: "Sea Breeze" },
  { value: "Yeni Balaxanı", label: "Yeni Balaxanı" },
  { value: "Yeni Ramana", label: "Yeni Ramana" },
  { value: "Zabrat", label: "Zabrat" },
  { value: "20-ci sahə", label: "20-ci sahə" },
  { value: "Badamdar", label: "Badamdar" },
  { value: "Bayıl", label: "Bayıl" },
  { value: "Bibiheybət", label: "Bibiheybət" },
  { value: "Şıxov", label: "Şıxov" },
  { value: "Bahar", label: "Bahar" },
  { value: "Bülbülə", label: "Bülbülə" },
  { value: "Dədə Qorqud", label: "Dədə Qorqud" },
  { value: "Əmircan", label: "Əmircan" },
  { value: "Günəşli", label: "Günəşli" },
  { value: "Hövsan", label: "Hövsan" },
  { value: "Qaraçuxur", label: "Qaraçuxur" },
  { value: "Massiv A", label: "Massiv A" },
  { value: "Massiv B", label: "Massiv B" },
  { value: "Massiv D", label: "Massiv D" },
  { value: "Massiv G", label: "Massiv G" },
  { value: "Massiv V", label: "Massiv V" },
  { value: "Suraxanı", label: "Suraxanı" },
  { value: "Şərq", label: "Şərq" },
  { value: "Yeni Günəşli", label: "Yeni Günəşli" },
  { value: "Yeni Suraxanı", label: "Yeni Suraxanı" },
  { value: "Zığ", label: "Zığ" },
  { value: "Yasamal", label: "Yasamal" },
  { value: "Yeni Yasamal", label: "Yeni Yasamal" },
];

export const azeCity = [
  { value: "Ağcabədi", label: "Ağcabədi" },
  { value: "Ağdaş", label: "Ağdaş" },
  { value: "Ağstafa", label: "Ağstafa" },
  { value: "Ağsu", label: "Ağsu" },
  { value: "Astara", label: "Astara" },
  { value: "Bakı", label: "Bakı" },
  { value: "Balakən", label: "Balakən" },
  { value: "Beyləqan", label: "Beyləqan" },
  { value: "Bərdə", label: "Bərdə" },
  { value: "Biləsuvar", label: "Biləsuvar" },
  { value: "Cəlilabad", label: "Cəlilabad" },
  { value: "Daşkəsən", label: "Daşkəsən" },
  { value: "Gədəbəy", label: "Gədəbəy" },
  { value: "Gəncə", label: "Gəncə" },
  { value: "Goranboy", label: "Goranboy" },
  { value: "Göyçay", label: "Göyçay" },
  { value: "Göygöl", label: "Göygöl" },
  { value: "Hacıqabul", label: "Hacıqabul" },
  { value: "Xaçmaz", label: "Xaçmaz" },
  { value: "Xırdalan", label: "Xırdalan" },
  { value: "Xızı", label: "Xızı" },
  { value: "Xocalı", label: "Xocalı" },
  { value: "Xudat", label: "Xudat" },
  { value: "İmişli", label: "İmişli" },
  { value: "İsmayıllı", label: "İsmayıllı" },
  { value: "Kürdəmir", label: "Kürdəmir" },
  { value: "Qax", label: "Qax" },
  { value: "Qazax", label: "Qazax" },
  { value: "Qəbələ", label: "Qəbələ" },
  { value: "Qobustan", label: "Qobustan" },
  { value: "Quba", label: "Quba" },
  { value: "Qusar", label: "Qusar" },
  { value: "Lerik", label: "Lerik" },
  { value: "Lənkəran", label: "Lənkəran" },
  { value: "Masallı", label: "Masallı" },
  { value: "Mingəçevir", label: "Mingəçevir" },
  { value: "Naxçıvan", label: "Naxçıvan" },
  { value: "Neftçala", label: "Neftçala" },
  { value: "Oğuz", label: "Oğuz" },
  { value: "Saatlı", label: "Saatlı" },
  { value: "Sabirabad", label: "Sabirabad" },
  { value: "Salyan", label: "Salyan" },
  { value: "Samux", label: "Samux" },
  { value: "Siyəzən", label: "Siyəzən" },
  { value: "Sumqayıt", label: "Sumqayıt" },
  { value: "Şabran", label: "Şabran" },
  { value: "Şamaxı", label: "Şamaxı" },
  { value: "Şəki", label: "Şəki" },
  { value: "Şəmkir", label: "Şəmkir" },
  { value: "Şirvan", label: "Şirvan" },
  { value: "Şuşa", label: "Şuşa" },
  { value: "Tərtər", label: "Tərtər" },
  { value: "Tovuz", label: "Tovuz" },
  { value: "Ucar", label: "Ucar" },
  { value: "Yardımlı", label: "Yardımlı" },
  { value: "Yevlax", label: "Yevlax" },
  { value: "Zaqatala", label: "Zaqatala" },
];

export const azeDistrict = [
  { value: "Abşeron", label: "Abşeron" },
  { value: "Binəqədi", label: "Binəqədi" },
  { value: "Xətai", label: "Xətai" },
  { value: "Xəzər", label: "Xəzər" },
  { value: "Qaradağ", label: "Qaradağ" },
  { value: "Nərimanov", label: "Nərimanov" },
  { value: "Nəsimi", label: "Nəsimi" },
  { value: "Nizami", label: "Nizami" },
  { value: "Pirallahı", label: "Pirallahı" },
  { value: "Sabunçu", label: "Sabunçu" },
  { value: "Səbail", label: "Səbail" },
  { value: "Suraxanı", label: "Suraxanı" },
  { value: "Yasamal", label: "Yasamal" },
];

export const azeMetro = [
  { value: "20 Yanvar", label: "20 Yanvar" },
  { value: "28 May", label: "28 May" },
  { value: "8 Noyabr", label: "8 Noyabr" },
  { value: "Avtovağzal", label: "Avtovağzal" },
  { value: "Azadlıq Prospekti", label: "Azadlıq Prospekti" },
  { value: "Bakmil", label: "Bakmil" },
  { value: "Dərnəgül", label: "Dərnəgül" },
  { value: "Elmlər Akademiyası", label: "Elmlər Akademiyası" },
  { value: "Əhmədli", label: "Əhmədli" },
  { value: "Gənclik", label: "Gənclik" },
  { value: "Həzi Aslanov", label: "Həzi Aslanov" },
  { value: "Xalqlar Dostluğu", label: "Xalqlar Dostluğu" },
  { value: "Xocəsən", label: "Xocəsən" },
  { value: "İçəri Şəhər", label: "İçəri Şəhər" },
  { value: "İnşaatçılar", label: "İnşaatçılar" },
  { value: "Koroğlu", label: "Koroğlu" },
  { value: "Qara Qarayev", label: "Qara Qarayev" },
  { value: "Memar Əcəmi", label: "Memar Əcəmi" },
  { value: "Neftçilər", label: "Neftçilər" },
  { value: "Nəriman Nərimanov", label: "Nəriman Nərimanov" },
  { value: "Nəsimi", label: "Nəsimi" },
  { value: "Nizami", label: "Nizami" },
  { value: "Sahil", label: "Sahil" },
  { value: "Şah İsmayıl Xətai", label: "Şah İsmayıl Xətai" },
  { value: "Ulduz", label: "Ulduz" },
];
